let models=[
 {id:1,title:'Organizador modular de escritorio',tags:'organizador · hogar · paramétrico',image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',url:'https://cults3d.com'},
 {id:2,title:'Maceta geométrica con drenaje',tags:'maceta · plantas · decoración',image:'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',url:'https://cults3d.com'},
 {id:3,title:'Miniatura de dragón articulado',tags:'dragón · miniatura · articulado',image:'https://images.unsplash.com/photo-1614732414444-096e5f112c0d?w=800&q=80',url:'https://cults3d.com'},
 {id:4,title:'Soporte para auriculares',tags:'soporte · escritorio · gaming',image:'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80',url:'https://cults3d.com'},
 {id:5,title:'Lámpara lunar decorativa',tags:'lámpara · hogar · regalo',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',url:'https://cults3d.com'},
 {id:6,title:'Caja de herramientas compacta',tags:'caja · herramientas · modular',image:'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800&q=80',url:'https://cults3d.com'}
];
let selected=new Set(),queue=[];
const $=s=>document.querySelector(s);
function render(){const query=$('#search').value.toLowerCase();const visible=models.filter(m=>(m.title+m.tags).toLowerCase().includes(query));$('#models').innerHTML=visible.map(m=>`<article class="model-card ${selected.has(m.id)?'selected':''}" data-id="${m.id}"><input class="card-check" type="checkbox" ${selected.has(m.id)?'checked':''}/><img src="${m.image}" alt="${m.title}"><div class="body"><h4>${m.title}</h4><div class="tags">${m.tags}</div></div></article>`).join('');document.querySelectorAll('.model-card').forEach(c=>c.onclick=e=>{if(e.target.type!=='checkbox')e.preventDefault();const id=+c.dataset.id;selected.has(id)?selected.delete(id):selected.add(id);render()});$('#selectionTitle').textContent=selected.size?`${selected.size} seleccionados`:'Tus modelos';$('#selectAll').checked=visible.length>0&&visible.every(m=>selected.has(m.id));renderQueue()}
function renderQueue(){const items=queue.length?queue:models.filter(m=>selected.has(m.id));$('#queueCount').textContent=items.length;$('#queueItems').innerHTML=items.length?items.map(m=>`<div class="queue-item"><img src="${m.image}"><div><strong>${m.title}</strong><span>${m.status||'Borrador · enlace a Cults3D'}</span></div></div>`).join(''):'<div class="empty">Selecciona modelos para verlos aquí.</div>'}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
$('#search').oninput=render;$('#selectAll').onchange=e=>{const q=$('#search').value.toLowerCase();models.filter(m=>(m.title+m.tags).toLowerCase().includes(q)).forEach(m=>e.target.checked?selected.add(m.id):selected.delete(m.id));render()};$('#generateBtn').onclick=async()=>{if(!selected.size)return toast('Selecciona al menos un modelo');const m=models.find(x=>selected.has(x.id));toast('Generando textos con IA…');try{const r=await fetch('/api/ai/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:m.title,description:m.tags,tags:m.tags.split(' · '),url:m.url})});if(!r.ok)throw new Error();const data=await r.json();m.ai=data;toast('Textos generados: '+data.title)}catch(e){toast('No se pudo generar el texto todavía')}};$('#prepareBtn').onclick=()=>{if(!selected.size)return toast('Selecciona al menos un modelo');queue=models.filter(m=>selected.has(m.id)).map(m=>({...m,status:m.ai?'Texto IA listo para revisar':'Listo para revisar'}));renderQueue();toast(`${queue.length} publicaciones preparadas`)};$('#publishBtn').onclick=()=>{if(!queue.length)return toast('Primero prepara la cola');queue=queue.map(m=>({...m,status:'Publicado · demo'}));$('#publishedCount').textContent=queue.length;renderQueue();toast('Publicaciones simuladas correctamente')};$('#connectBtn').onclick=()=>{window.location.href='https://elysium3d-publisher.pages.dev/api/auth/start'};render();
function normalizeCults(payload){const rows=payload?.data?.creations||[];return rows.filter(m=>m.creator?.nick?.toLowerCase()==='elysium3d').map((m,i)=>{const images=(m.illustrations||[]).map(x=>typeof x==='string'?x:x.url).filter(Boolean);return {id:`cults-${i}-${m.url||m.name}`,title:m.name||'Modelo de Cults3D',tags:Array.isArray(m.tags)?m.tags.join(' · '):(m.tags||''),description:m.description||'',image:images[0]||'',images,url:m.url||'https://cults3d.com/es/usuarios/Elysium3d/modelos-3d'}})}
$('#syncBtn').onclick=async()=>{toast('Sincronizando Cults3D…');try{const r=await fetch('/api/cults/models');const data=await r.json();if(!r.ok||data.errors)throw new Error(data.errors?.[0]?.message||'No se pudo leer Cults3D');const imported=normalizeCults(data);if(!imported.length)throw new Error('No se encontraron modelos');models=imported;selected.clear();queue=[];render();toast(`${imported.length} modelos importados con sus imágenes`)}catch(e){toast(e.message||'No se pudo sincronizar Cults3D')}};
